/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DataTable: typeof import('./src/components/Product/DataTable.vue')['default']
    EditItemDialog: typeof import('./src/components/Product/EditItemDialog.vue')['default']
    Footer: typeof import('./src/components/Layouts/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navbar: typeof import('./src/components/Layouts/Navbar.vue')['default']
    Navigasi: typeof import('./src/components/Layouts/Navigasi.vue')['default']
    Sidebar: typeof import('./src/components/Layouts/Sidebar.vue')['default']
    Table: typeof import('./src/components/Product/Table.vue')['default']
  }
}
