/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./src/components/dashboard/BarChart.vue')['default']
    CardGroup: typeof import('./src/components/dashboard/CardGroup.vue')['default']
    CategorieTable: typeof import('./src/components/categorie/CategorieTable.vue')['default']
    DonutChart: typeof import('./src/components/dashboard/DonutChart.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LineChart: typeof import('./src/components/dashboard/LineChart.vue')['default']
    Navigasi: typeof import('./src/components/Navigasi.vue')['default']
    OrderTable: typeof import('./src/components/order/OrderTable.vue')['default']
    ProductTable: typeof import('./src/components/product/ProductTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserTable: typeof import('./src/components/user/UserTable.vue')['default']
  }
}
